apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: kafka-console
  namespace: kafka-cdc
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  hostname: kafka-console-kafka-cdc.{{ .Values.clusterDomain }}
  kafkaClusters:
    - name: cdc-cluster
      namespace: kafka-cdc
      listener: plain
