apiVersion: camel.apache.org/v1
kind: IntegrationPlatform
metadata:
  name: camel-k
  namespace: industrial-edge-stormshift-messaging
  labels:
    app: "camel-k"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  configuration:
  - type: repository
    value: https://maven.repository.redhat.com/earlyaccess/all@id=redhat.ea
  build:
    baseImage: registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
    registry:
      address: image-registry.openshift-image-registry.svc:5000
      insecure: true
      organization: industrial-edge-stormshift-messaging
      secret: camel-k-registry-secret
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-k-operator-registry-editor
  namespace: industrial-edge-stormshift-messaging
subjects:
  - kind: ServiceAccount
    name: camel-k-operator
    namespace: industrial-edge-stormshift-messaging
  - kind: ServiceAccount
    name: default
    namespace: industrial-edge-stormshift-messaging
roleRef:
  kind: ClusterRole
  name: registry-editor
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: camel-k-operator-registry-viewer
  namespace: industrial-edge-stormshift-messaging
subjects:
  - kind: ServiceAccount
    name: camel-k-operator
    namespace: industrial-edge-stormshift-messaging
  - kind: ServiceAccount
    name: default
    namespace: industrial-edge-stormshift-messaging
roleRef:
  kind: ClusterRole
  name: registry-viewer
  apiGroup: rbac.authorization.k8s.io
