apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: openshift-gitops-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  controller:
    resources:
      limits:
        cpu: "4"
        memory: 6Gi
      requests:
        cpu: 500m
        memory: 2Gi
    env:
      - name: ARGOCD_CONTROLLER_REPLICAS
        value: "1"
  repo:
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi
  server:
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 125m
        memory: 256Mi
