apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.uniqueName }}
  description: ${{ values.description }}
  annotations:
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{ values.uniqueName }}
  tags:
    - java
    - quarkus
    - mcp
    - kubernetes
    - openshift
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
