---
apiVersion: v1
kind: Secret
metadata:
  name: camel-k-operator
  namespace: manuela-stormshift-messaging
  annotations:
    kubernetes.io/service-account.name: camel-k-operator
type: kubernetes.io/service-account-token
