---
apiVersion: v1
kind: Secret
metadata:
  name: s3-anomaly
  namespace: manuela-data-lake
type: Opaque
stringData:
  application.properties: |
    AWS_SECRET_ACCESS_KEY: minioadmin
    AWS_ACCESS_KEY_ID: minioadmin
