---
apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-user-bucket
  namespace: manuela-inference
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
type: Opaque
stringData:
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_S3_BUCKET: user-bucket
  AWS_S3_ENDPOINT: http://minio.manuela-ml-workspace.svc:9000
  AWS_DEFAULT_REGION: us-east-1
