{{- range $i := list "pipeline-bucket" "user-bucket" }}
{{- range $j := list "ml-development" "manuela-tst-all" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-{{ $i }}
  namespace: {{ $j }}
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
type: Opaque
stringData:
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_S3_BUCKET: {{ $i }}
  AWS_S3_ENDPOINT: {{ $.Values.s3.default_endpoint }}
  AWS_DEFAULT_REGION: {{ $.Values.s3.default_region }}
{{- end }}
{{- end }}
