quarkus.http.port=8080
quarkus.log.level=INFO
quarkus.devservices.enabled=false

camel.main.routes-include-pattern=classpath:routes/*.camel.yaml

# OpenShift deployment (activated with -Popenshift)
quarkus.openshift.route.expose=true
quarkus.container-image.group=${{ values.namespace }}
quarkus.kubernetes-client.trust-certs=true
