apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${{values.uniqueName}}-image-builder
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${{values.namespace}}
  - kind: ServiceAccount
    name: camel-k-operator
    namespace: ${{values.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
