clusterDomain: apps.cluster.example.com

kafka:
  s3:
    bucket: anomaly-detection
    endpointurl: http://minio.manuela-ml-workspace.svc:9000
    message:
      aggregation:
        count: 50
  broker:
    uri: "prod-cluster-kafka-bootstrap.manuela-data-lake.svc:9092"
    topic:
      temperature: "factory-cluster.manuela-stormshift-messaging.iot-sensor-sw-temperature"
      vibration: "factory-cluster.manuela-stormshift-messaging.iot-sensor-sw-vibration"
