apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret-and-branch
  namespace: ml-development
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  GITEA_HOSTNAME: "{{ .Values.global.git.hostname }}"
  GITEA_USER: "{{ .Values.global.git.account }}"
  GITEA_TOKEN: ""
  GIT_BRANCH: "{{ .Values.global.git.dev_revision }}"
