{{- $giturl := printf "https://gitea-gitea.%s/" .Values.clusterDomain }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret
  namespace: manuela-ci
  annotations:
    tekton.dev/git-0: {{ $giturl }}
type: kubernetes.io/basic-auth
stringData:
  username: "gitea_admin"
  password: "openshift"
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-admin-secret-and-branch
  namespace: ml-development
  annotations:
    tekton.dev/git-0: {{ $giturl }}
type: Opaque
stringData:
  username: "gitea_admin"
  password: "openshift"
  branch: "main"
