---
type: showroom

default_width: 35
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: Console
    url: 'https://console-openshift-console.{cluster_domain}'

  - name: DevSpaces
    url: 'https://devspaces.{cluster_domain}'

  - name: Gitea
    url: 'https://gitea-gitea.{cluster_domain}'

  - name: Developer Hub
    url: 'https://backstage-developer-hub-developer-hub.{cluster_domain}'

  - name: Kafka Console
    url: 'https://kafka-console-kafka-cdc.{cluster_domain}'

  - name: Grafana
    url: 'https://grafana-observability.{cluster_domain}'
