apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: Software Templates for Developer Hub
spec:
  targets:
    - ./customer-service-mcp/template.yaml
    - ./remove-component/template.yaml
    - ./camel-kaoto/template.yaml
    - ./sonataflow-bpm/template.yaml
    - ./kafka-cdc-mcp/template.yaml
    - ./k8s-ops-mcp/template.yaml
    - ./industrial-edge/template.yaml
    - ./kafka-external-consumer/template.yaml
